version: 2
jobs:
  build:
    docker:
        - image: circleci/node:9.10-stretch
    steps:
        - checkout
        - restore_cache:
            keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
        # - run: yarn 
        # - run: yarn build
        - save_cache:
            paths:
              - node_modules
            key: v1-dependencies-{{ checksum "package.json" }}
  test:
    docker:
      - image: karthikiyengar/node-nightwatch:0.0.1
    steps:
      - checkout
      # - run: sudo su -c 'echo "deb http://deb.debian.org/debian jessie-backports main" >> /etc/apt/sources.list'
      # - run: |
      #     sudo rm -rf /var/lib/apt/lists/*
      #     sudo apt-get update
      #     sudo apt install -t jessie-backports  openjdk-8-jre-headless ca-certificates-java
      - run:
          name: Install Nightwatch
          command: sudo npm install -g nightwatch
      - run:
          name: Launch tests
          command: cd tests/Integration; nightwatch src/tests/reservationPopIn.js
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build